sonar.projectKey=openroof-frontend
sonar.sources=src

# Aquí agregué la carpeta E2E a las exclusiones para que ignore los tests de Cypress
sonar.exclusions=node_modules/**,dist/**,public/**,E2E/**,**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

sonar.javascript.environments=browser,node