export const AGENTS = [
  {
    id: 1,
    name: "Ayumu Sonoda",
    role: "Agente Inmobiliario Senior",
    company: "Valorant Real State PY",
    priceRange: "$75K – $2.4M price range",
    stats: "25 sales last 12 months",
    rating: 5.0,
    reviews: 60,
    city: "Encarnación",
    department: "Itapúa",
    sold: 31,
    rented: 18,
    avgRentPrice: 680000,
    specializations: [
      "Departamentos",
      "Casas",
      "Inversiones",
      "Asesoría legal",
      "Rentas",
    ],
  },
  {
    id: 2,
    name: "Carlos Martínez",
    role: "Agente Inmobiliario Senior",
    company: "Valorant Real State PY",
    priceRange: "$75K – $2.4M price range",
    stats: "25 sales last 12 months",
    rating: 4.6,
    reviews: 34,
    city: "Asunción",
    department: "Central",
    sold: 45,
    rented: 23,
    avgRentPrice: 750000,
    specializations: [
      "Departamentos",
      "Casas",
      "Comercial",
      "Rentas",
      "Inversiones",
    ],
  },
  {
    id: 3,
    name: "Nicolás Ortiz",
    role: "Agente Inmobiliario",
    company: "OpenRoof Realty",
    priceRange: "$75K – $2.4M price range",
    stats: "25 sales last 12 months",
    rating: 4.2,
    reviews: 18,
    city: "Ciudad del Este",
    department: "Alto Paraná",
    sold: 22,
    rented: 9,
    avgRentPrice: 540000,
    specializations: ["Casas", "Terrenos", "Rentas", "Asesoría", "CDE"],
  },
  {
    id: 4,
    name: "Otto Enzler",
    role: "Broker Inmobiliario",
    company: "Build Partners",
    priceRange: "$75K – $2.4M price range",
    stats: "20 sales last 12 months",
    rating: 4.8,
    reviews: 80,
    city: "Encarnación",
    department: "Itapúa",
    sold: 38,
    rented: 30,
    avgRentPrice: 920000,
    specializations: ["Lujo", "Inversiones", "Comercial", "Rentas", "Proyectos"],
  },
  {
    id: 5,
    name: "Manuel Ayala",
    role: "Agente Inmobiliario",
    company: "Central Homes",
    priceRange: "$75K – $2.4M price range",
    stats: "20 sales last 12 months",
    rating: 3.9,
    reviews: 52,
    city: "San Lorenzo",
    department: "Central",
    sold: 17,
    rented: 21,
    avgRentPrice: 610000,
    specializations: ["Rentas", "Casas", "Estudiantes", "San Lorenzo"],
  },
  {
    id: 6,
    name: "Agustín Argüello",
    role: "Agente Inmobiliario",
    company: "Central Homes",
    priceRange: "$75K – $2.4M price range",
    stats: "20 sales last 12 months",
    rating: 4.0,
    reviews: 11,
    city: "Luque",
    department: "Central",
    sold: 12,
    rented: 8,
    avgRentPrice: 430000,
    specializations: ["Casas", "Terrenos", "Primera vivienda", "Luque"],
  },
  {
    id: 7,
    name: "Valeria Duarte",
    role: "Agente Inmobiliario Senior",
    company: "OpenRoof Realty",
    priceRange: "$50K – $900K price range",
    stats: "14 sales last 12 months",
    rating: 4.9,
    reviews: 95,
    city: "Asunción",
    department: "Central",
    sold: 29,
    rented: 34,
    avgRentPrice: 880000,
    specializations: ["Rentas", "Departamentos", "Lujo", "Asunción"],
  },
  {
    id: 8,
    name: "Jorge Benítez",
    role: "Agente Inmobiliario",
    company: "Build Partners",
    priceRange: "$60K – $1.6M price range",
    stats: "19 sales last 12 months",
    rating: 4.4,
    reviews: 41,
    city: "Fernando de la Mora",
    department: "Central",
    sold: 24,
    rented: 16,
    avgRentPrice: 590000,
    specializations: ["Casas", "Rentas", "Familias", "FDM"],
  },
  {
    id: 9,
    name: "Camila Ríos",
    role: "Agente Inmobiliario",
    company: "Río Real Estate",
    priceRange: "$45K – $1.1M price range",
    stats: "12 sales last 12 months",
    rating: 3.6,
    reviews: 27,
    city: "Lambaré",
    department: "Central",
    sold: 10,
    rented: 14,
    avgRentPrice: 410000,
    specializations: ["Rentas", "Departamentos", "Lambaré"],
  },
  {
    id: 10,
    name: "Bruno Ferreira",
    role: "Agente Inmobiliario",
    company: "OpenRoof Realty",
    priceRange: "$80K – $2.0M price range",
    stats: "22 sales last 12 months",
    rating: 4.1,
    reviews: 63,
    city: "Encarnación",
    department: "Itapúa",
    sold: 20,
    rented: 12,
    avgRentPrice: 720000,
    specializations: ["Proyectos", "Comercial", "Rentas", "Encarnación"],
  },
  {
    id: 11,
    name: "Sofía Álvarez",
    role: "Agente Inmobiliario Junior",
    company: "Central Homes",
    priceRange: "$70K – $1.8M price range",
    stats: "16 sales last 12 months",
    rating: 3.2,
    reviews: 14,
    city: "Capiatá",
    department: "Central",
    sold: 8,
    rented: 6,
    avgRentPrice: 360000,
    specializations: ["Primera vivienda", "Capiatá", "Casas"],
  },
  {
    id: 12,
    name: "Diego Acosta",
    role: "Agente Inmobiliario",
    company: "Guairá Realty",
    priceRange: "$40K – $850K price range",
    stats: "9 sales last 12 months",
    rating: 2.7,
    reviews: 9,
    city: "Villarrica",
    department: "Guairá",
    sold: 6,
    rented: 4,
    avgRentPrice: 280000,
    specializations: ["Terrenos", "Villarrica", "Rentas"],
  },
];

export const TYPE_OPTIONS = [
  { value: "", label: "Todos los tipos" },
  { value: "rentas", label: "Rentas" },
  { value: "casas", label: "Casas" },
  { value: "departamentos", label: "Departamentos" },
  { value: "inversiones", label: "Inversiones" },
  { value: "comercial", label: "Comercial" },
  { value: "terrenos", label: "Terrenos" },
];
