export const MOCK_AGENTS = [
  {
    id: 1,
    name: "Ayumu Sonoda",
    role: "Agente Inmobiliario Senior",
    company: "Valorant Real State PY",
    rating: 5.0,
    reviews: 60,
    city: "Encarnación",
    department: "Itapúa",
    sold: 31,
    rented: 18,
    avgRentPrice: 680000,
    specializations: [
      "Departamentos",
      "Casas",
      "Inversiones",
      "Asesoría legal",
      "Rentas",
    ],
    type: "rentas",
    email: "ayumu@valorant.com.py",
    nickName: "AS",
    gender: "prefiero-no-decir",
    country: "Paraguay",
    languages: ["Español", "Inglés"],
    timeZone: "UTC -03:00",
    bio: "Agente inmobiliario enfocado en brindar una experiencia clara y segura en cada etapa del proceso.",
    photoUrl: "",
  },
  {
    id: 2,
    name: "Carlos Martínez",
    role: "Agente Inmobiliario Senior",
    company: "Valorant Real State PY",
    rating: 4.6,
    reviews: 34,
    city: "Asunción",
    department: "Central",
    sold: 45,
    rented: 23,
    avgRentPrice: 750000,
    specializations: ["Departamentos", "Casas", "Comercial", "Rentas", "Inversiones"],
    type: "residencial",
    email: "carlos@valorant.com.py",
    nickName: "CM",
    gender: "masculino",
    country: "Paraguay",
    languages: ["Español"],
    timeZone: "UTC -03:00",
    bio: "Especialista en propiedades residenciales y acompañamiento integral para compra/venta y alquiler.",
    photoUrl: "",
  },
  {
    id: 3,
    name: "Nicolás Ortiz",
    role: "Agente Inmobiliario",
    company: "OpenRoof Realty",
    rating: 4.2,
    reviews: 18,
    city: "Ciudad del Este",
    department: "Alto Paraná",
    sold: 22,
    rented: 9,
    avgRentPrice: 540000,
    specializations: ["Casas", "Terrenos", "Rentas", "Asesoría", "CDE"],
    type: "comercial",
    email: "nicolas@openroof.com",
    nickName: "NO",
    gender: "masculino",
    country: "Paraguay",
    languages: ["Español", "Portugués"],
    timeZone: "UTC -03:00",
    bio: "Conocimiento de mercado local y enfoque en oportunidades para inversión y terrenos.",
    photoUrl: "",
  },
  {
    id: 4,
    name: "Otto Enzler",
    role: "Broker Inmobiliario",
    company: "Build Partners",
    rating: 4.8,
    reviews: 80,
    city: "Encarnación",
    department: "Itapúa",
    sold: 38,
    rented: 30,
    avgRentPrice: 920000,
    specializations: ["Lujo", "Inversiones", "Comercial", "Rentas", "Proyectos"],
    type: "lujo",
    email: "otto@build.com.py",
    nickName: "OE",
    gender: "masculino",
    country: "Paraguay",
    languages: ["Español", "Inglés"],
    timeZone: "UTC -03:00",
    bio: "Broker con foco en inversiones, propiedades premium y acompañamiento en proyectos.",
    photoUrl: "",
  },
  {
    id: 5,
    name: "Manuel Ayala",
    role: "Agente Inmobiliario",
    company: "Central Homes",
    rating: 3.9,
    reviews: 52,
    city: "San Lorenzo",
    department: "Central",
    sold: 17,
    rented: 21,
    avgRentPrice: 610000,
    specializations: ["Rentas", "Casas", "Estudiantes", "San Lorenzo"],
    type: "rentas",
    email: "manuel@centralhomes.com",
    nickName: "MA",
    gender: "masculino",
    country: "Paraguay",
    languages: ["Español"],
    timeZone: "UTC -03:00",
    bio: "Acompaño procesos de renta y compra de vivienda con asesoría cercana y rápida.",
    photoUrl: "",
  },
  {
    id: 6,
    name: "Agustín Argüello",
    role: "Agente Inmobiliario",
    company: "Central Homes",
    rating: 4.0,
    reviews: 11,
    city: "Luque",
    department: "Central",
    sold: 12,
    rented: 8,
    avgRentPrice: 430000,
    specializations: ["Casas", "Terrenos", "Primera vivienda", "Luque"],
    type: "residencial",
    email: "agustin@centralhomes.com",
    nickName: "AA",
    gender: "masculino",
    country: "Paraguay",
    languages: ["Español"],
    timeZone: "UTC -03:00",
    bio: "Enfoque en primera vivienda y acompañamiento a clientes en todo el proceso.",
    photoUrl: "",
  },
  {
    id: 7,
    name: "Valeria Duarte",
    role: "Agente Inmobiliario Senior",
    company: "OpenRoof Realty",
    rating: 4.9,
    reviews: 95,
    city: "Asunción",
    department: "Central",
    sold: 29,
    rented: 34,
    avgRentPrice: 880000,
    specializations: ["Rentas", "Departamentos", "Lujo", "Asunción"],
    type: "lujo",
    email: "valeria@openroof.com",
    nickName: "VD",
    gender: "femenino",
    country: "Paraguay",
    languages: ["Español", "Inglés"],
    timeZone: "UTC -03:00",
    bio: "Especialista en alquileres y propiedades premium en Asunción.",
    photoUrl: "",
  },
  {
    id: 8,
    name: "Jorge Benítez",
    role: "Agente Inmobiliario",
    company: "Build Partners",
    rating: 4.4,
    reviews: 41,
    city: "Fernando de la Mora",
    department: "Central",
    sold: 24,
    rented: 16,
    avgRentPrice: 590000,
    specializations: ["Casas", "Rentas", "Familias", "FDM"],
    type: "residencial",
    email: "jorge@build.com.py",
    nickName: "JB",
    gender: "masculino",
    country: "Paraguay",
    languages: ["Español"],
    timeZone: "UTC -03:00",
    bio: "Trabajo con familias y residenciales, priorizando comunicación y transparencia.",
    photoUrl: "",
  },
  {
    id: 9,
    name: "Camila Ríos",
    role: "Agente Inmobiliario",
    company: "Río Real Estate",
    rating: 3.6,
    reviews: 27,
    city: "Lambaré",
    department: "Central",
    sold: 10,
    rented: 14,
    avgRentPrice: 410000,
    specializations: ["Rentas", "Departamentos", "Lambaré"],
    type: "rentas",
    email: "camila@riorealestate.com",
    nickName: "CR",
    gender: "femenino",
    country: "Paraguay",
    languages: ["Español"],
    timeZone: "UTC -03:00",
    bio: "Enfoque en alquileres y departamentos, con seguimiento continuo.",
    photoUrl: "",
  },
  {
    id: 10,
    name: "Bruno Ferreira",
    role: "Agente Inmobiliario",
    company: "OpenRoof Realty",
    rating: 4.1,
    reviews: 63,
    city: "Encarnación",
    department: "Itapúa",
    sold: 20,
    rented: 12,
    avgRentPrice: 720000,
    specializations: ["Proyectos", "Comercial", "Rentas", "Encarnación"],
    type: "comercial",
    email: "bruno@openroof.com",
    nickName: "BF",
    gender: "masculino",
    country: "Paraguay",
    languages: ["Español", "Portugués"],
    timeZone: "UTC -03:00",
    bio: "Apoyo a clientes en proyectos y propiedades comerciales con análisis de rentabilidad.",
    photoUrl: "",
  },
  {
    id: 11,
    name: "Sofía Álvarez",
    role: "Agente Inmobiliario Junior",
    company: "Central Homes",
    rating: 3.2,
    reviews: 14,
    city: "Capiatá",
    department: "Central",
    sold: 8,
    rented: 6,
    avgRentPrice: 360000,
    specializations: ["Primera vivienda", "Capiatá", "Casas"],
    type: "residencial",
    email: "sofia@centralhomes.com",
    nickName: "SA",
    gender: "femenino",
    country: "Paraguay",
    languages: ["Español"],
    timeZone: "UTC -03:00",
    bio: "Agente junior con foco en primera vivienda y atención personalizada.",
    photoUrl: "",
  },
  {
    id: 12,
    name: "Diego Acosta",
    role: "Agente Inmobiliario",
    company: "Guairá Realty",
    rating: 2.7,
    reviews: 9,
    city: "Villarrica",
    department: "Guairá",
    sold: 6,
    rented: 4,
    avgRentPrice: 280000,
    specializations: ["Terrenos", "Villarrica", "Rentas"],
    type: "comercial",
    email: "diego@guairarealty.com",
    nickName: "DA",
    gender: "masculino",
    country: "Paraguay",
    languages: ["Español"],
    timeZone: "UTC -03:00",
    bio: "Asesoría en terrenos y oportunidades locales en Guairá.",
    photoUrl: "",
  },
];

