name: Análisis de Calidad - Frontend Vite

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: Build and Analyze
    runs-on: ubuntu-latest
    
    # Seguridad: Principio de menor privilegio
    permissions:
      contents: read
    
    steps:
      - name: Descargar el código fuente
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          persist-credentials: false

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          # Pasamos la URL directamente, asegurándonos de incluir https://
          SONAR_HOST_URL: "https://sonaropenroof.duckdns.org"
          # El token sigue oculto, pero debes asegurarte de que exista en los secretos de Dependabot
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}